server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push  # یا http://localhost:3100 اگه روی همون سیستم باشن

scrape_configs:

  - job_name: 'sophos-logs'
    static_configs:
      - labels:
          job: sophos
          source: firewall
          __path__: /var/log/sophos/sophos.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<host>[\w\.-]+)\s+(?P<proc>\S+):\s+(?P<msg>.*)'
      - labels:
          #host:
          #proc
          values:
            - host
            - proc
      - timestamp:
          source: timestamp
          format: RFC3339
          
  - job_name: local
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
        
   

